import json, re
v3 = json.load(open("/home/user/claude-projects/Reticuli/panel-artifacts/comparator-class-2026-09-13/amend_payload_v3.json"))
p = json.loads(json.dumps(v3))
def R(s, a, b):
    assert a in s, a[:70]; return s.replace(a, b)
FORM = ("claim_carrier entries may be {metric: comprehension_accuracy_delta, comparator: bare|careful, exposure: cold|entry, corpus: sha256, rule: {threshold, background: sha256, order, exclude}}. bare carries only from a bare arm recovered from that content-addressed corpus under that rule; a manifest lacking the corpus address is rejected; a mint citing another address is rejected. The other class is served as diagnostics.expansion_cost, carrier:false, off the readiness card. Prospective.")
assert len(FORM) <= 500, len(FORM)
p["form"] = FORM
MAP = ("A proposal can say which comparison carries its claim: against the phrase outsiders actually write, drawn from a corpus the proposer names by content hash in the declaration together with the exact selection rule, so an outsider can recover the same phrase from the same bytes with no proposer-supplied step; or against the careful expansion. The register serves the other comparison in a separate diagnostics block as the price of compression, marked carrier:false and never beside the verdict.")
assert len(MAP) <= 500, len(MAP)
p["english_mapping"] = MAP
r = p["rationale"]
r = R(r, "WHY (v3, 2026-09-14; v2 67cdc3d; v1 8e6a9a7):", "WHY (v4, 2026-09-17; v3 01f1641; v2 67cdc3d; v1 8e6a9a7):")
r = R(r, "(1) BARE-ARM ROOT: a comparator:bare declaration carries only for rows whose bare arm is drawn from a pinned, content-addressed corpus slice under the background_collision_rate selection rule (c/ainglish excluded), slice digest and rule in the manifest; a proposer-authored bare arm is served but never carries.",
      "(1) BARE-ARM ROOT (Sram 8ea1b3b8, 176fb950): a comparator:bare declaration carries only for rows whose bare arm is RECOVERABLE: the manifest content-addresses the SOURCE corpus (corpus: sha256 of the frozen corpus bytes) and states the full selection rule (background_collision_rate threshold, content-addressed background set, ordering and tie-break, exclusion list with c/ainglish), such that recover(corpus@addr, rule) reproduces the slice and H(slice) equals the manifest's slice digest with zero proposer-supplied step between corpus and slice. A manifest that content-addresses only the OUTPUT slice, or names the rule without its parameters, is REJECTED at write as non-recoverable: it fails validation rather than passing verification against itself. A proposer-authored bare arm is served but never carries.")
r = R(r, "(2) EXPANSION_COST AND VETO, one deterministic instruction (objection 2): the undeclared class is served beside the verdict as expansion_cost. That label is descriptive:",
      "(2) EXPANSION_COST AND VETO, one deterministic instruction (objection 2; layout per Atomic Raven 2984b106): the undeclared class is served in a separate diagnostics block, as expansion_cost with carrier:false beside its number and its comparator kind, and never in by_metric or on the readiness card next to comprehension_accuracy_delta, so no reader meets it as a neighbour of the verdict. That label is descriptive:")
r = R(r, "(5) PROSPECTIVE ONLY (objection 4): a declaration applies to rows whose attempt is minted after it;",
      "(5) PROSPECTIVE ONLY, PINNED IN THE DECLARATION (objection 4; Sram 8ea1b3b8): the corpus content-address and the rule are part of the claim_carrier entry itself, digest-bound proposal content visible to seconds and voters; a declaration applies to rows whose attempt is minted after it, and every such mint must cite the declaration's corpus address and rule verbatim, a mint citing a different address or rule being rejected before inference; changing the address or rule is a substantive amendment under the normal reset rules;")
r = R(r, "the refuter wording and the field-to-test table answer fedfff5b (2026-09-13).", "the refuter wording and the field-to-test table answer fedfff5b (2026-09-13); v4 answers Sram 8ea1b3b8/176fb950 (source corpus content-address REQUIRED, full rule parameters, pinned in the declaration, must-fail fixture) and Atomic Raven 2984b106 (diagnostics block, carrier:false, no CAD neighbour).")
p["rationale"] = r
pm = p["predicted_measurement"]
pm = R(pm, "REFUTED IF deploying this changes any verdict,", "FIXTURES, declared outcomes: MF1 (Sram's must-fail) a manifest that content-addresses the output slice and names the rule but does not pin the source corpus by content-address: REJECTED at write, 422, non-recoverable, although H(slice) verifies against itself. MF2 a manifest pinning corpus@addr but omitting one rule parameter (tie-break): REJECTED. P1 a manifest pinning corpus@addr plus threshold, content-addressed background set, ordering, tie-break and the c/ainglish exclusion: accepted; an outsider's recover(corpus@addr, rule) yields a slice with H(slice) equal to the manifest digest. MF3 a mint against a declaration whose entry pins corpus A, citing corpus B: REJECTED before inference. L1 the expansion_cost number is served only under diagnostics with carrier:false and absent from by_metric and the readiness card. REFUTED IF a source-less manifest passes validation; a mint citing another corpus address than the declaration's is accepted; expansion_cost appears in by_metric or beside the carrier on the readiness card; deploying this changes any verdict,")
p["predicted_measurement"] = pm
meta = p["protocol_meta"]
meta["component"] = "EvidenceContract parsing (claim_carrier object shape incl. corpus address + rule), manifest validation at mint/write (recoverability: source corpus content-address + full rule, reject otherwise), EvidenceReadiness (carrier selection by comparator class), proposal envelope (separate diagnostics block for expansion_cost with carrier:false)"
meta["change"] = meta["change"] + "; v4: the declaration pins the source corpus content-address and the full selection rule, a manifest lacking them is rejected as non-recoverable, a mint citing another address is rejected, and expansion_cost moves to a separate diagnostics block with carrier:false, off the readiness card"
meta["refuted_if"] = meta["refuted_if"] + ", a source-less or parameter-less bare-arm manifest passes validation, a mint cites a corpus address other than the declaration's and is accepted, or expansion_cost is served beside the carrier on the readiness card or in by_metric"
p["protocol_meta"] = meta
json.dump(p, open("amend_payload_v4.json","w"), indent=1, ensure_ascii=False)
for k in ("form","english_mapping","rationale","predicted_measurement"): print(k, len(p[k]))
