# Scenario banks: 7 declared domains x 8 scenarios.
# Fields: dom, n, lead, np/ns (noun), vp/vs (predicate pl/sg), vm (may-form),
#   pi (a-member-WITH-property, paraphrased), ni (a-member-WITHOUT-property, paraphrased),
#   sa (state: every member has property, phrased w/o all/every), sn (state: no member has property),
#   mp (members paraphrase for count/which questions), loc (location phrase).
# Paraphrase discipline: pi/ni/sa/sn/mp/loc must not reuse content words from lead or claims.
SC = [
# --- incidents ---
dict(dom="incidents", n=4, lead="Four services went down during the outage window.",
     np="services", ns="service", vp="recovered on their own", vs="recovered on its own", vm="may have recovered on its own",
     pi="a system that came back without help", ni="a system that needed manual intervention",
     sa="each affected system healed itself unaided", sn="no system healed itself and each needed an engineer",
     mp="systems", loc="after the incident"),
dict(dom="incidents", n=6, lead="The postmortem covers six alerts raised last night.",
     np="alerts", ns="alert", vp="were false alarms", vs="was a false alarm", vm="may have been a false alarm",
     pi="a warning that pointed at nothing real", ni="a warning that reflected a genuine problem",
     sa="every single warning turned out spurious", sn="each warning tracked a real fault",
     mp="warnings", loc="in the report"),
dict(dom="incidents", n=3, lead="Three deploys shipped during the freeze exception.",
     np="deploys", ns="deploy", vp="were rolled back", vs="was rolled back", vm="may have been rolled back",
     pi="a release that got reverted", ni="a release that stayed in production",
     sa="the entire batch of releases got reverted", sn="each release remained live untouched",
     mp="releases", loc="by morning"),
dict(dom="incidents", n=8, lead="Eight runbooks were exercised in the disaster drill.",
     np="runbooks", ns="runbook", vp="failed at the first step", vs="failed at its first step", vm="may have failed at its first step",
     pi="a procedure that broke immediately", ni="a procedure that got past its opening stage",
     sa="each procedure broke right at the start", sn="every procedure cleared its opening stage",
     mp="procedures", loc="during the drill"),
dict(dom="incidents", n=5, lead="Five engineers were paged about the checksum mismatch.",
     np="engineers", ns="engineer", vp="acknowledged the page", vs="acknowledged the page", vm="may have acknowledged the page",
     pi="a responder who reacted to the notification", ni="a responder who never reacted to the notification",
     sa="every responder reacted to the notification", sn="the notification drew no reaction from anyone",
     mp="responders", loc="within the hour"),
dict(dom="incidents", n=2, lead="Two datacenter feeds carried the traffic during failover.",
     np="feeds", ns="feed", vp="dropped packets", vs="dropped packets", vm="may have dropped packets",
     pi="a line that lost data in transit", ni="a line that delivered everything intact",
     sa="both lines lost data in transit", sn="each line delivered its data intact",
     mp="lines", loc="under failover"),
dict(dom="incidents", n=7, lead="Seven tickets were opened against the gateway timeout.",
     np="tickets", ns="ticket", vp="were duplicates", vs="was a duplicate", vm="may have been a duplicate",
     pi="a filing that repeated an existing report", ni="a filing with genuinely new content",
     sa="every filing repeated an existing report", sn="each filing contained genuinely new content",
     mp="filings", loc="in the tracker"),
dict(dom="incidents", n=12, lead="Twelve log segments span the corruption incident.",
     np="segments", ns="segment", vp="are unreadable", vs="is unreadable", vm="may be unreadable",
     pi="a chunk that cannot be parsed", ni="a chunk that parses cleanly",
     sa="the record is beyond parsing from end to end", sn="each chunk parses cleanly",
     mp="chunks", loc="in the archive"),
# --- replicas ---
dict(dom="replicas", n=6, lead="The ledger cluster keeps six replicas.",
     np="replicas", ns="replica", vp="are stale", vs="is stale", vm="may be stale",
     pi="a copy that has fallen behind", ni="a copy that is fully current",
     sa="every copy has fallen behind", sn="each copy is fully current",
     mp="copies", loc="in the cluster"),
dict(dom="replicas", n=3, lead="Three mirrors serve the package archive.",
     np="mirrors", ns="mirror", vp="are out of sync", vs="is out of sync", vm="may be out of sync",
     pi="a host serving outdated content", ni="a host serving fresh content",
     sa="every host is serving outdated content", sn="each host serves fresh content",
     mp="hosts", loc="on the network"),
dict(dom="replicas", n=5, lead="Five shards hold the user table.",
     np="shards", ns="shard", vp="passed the integrity check", vs="passed the integrity check", vm="may have passed the integrity check",
     pi="a partition that verified clean", ni="a partition that flunked verification",
     sa="each partition verified clean", sn="every partition flunked verification",
     mp="partitions", loc="in the database"),
dict(dom="replicas", n=2, lead="Two standby nodes back the primary.",
     np="nodes", ns="node", vp="are lagging", vs="is lagging", vm="may be lagging",
     pi="a backup running behind", ni="a backup keeping pace",
     sa="both backups are running behind", sn="each backup keeps pace",
     mp="backups", loc="behind the primary"),
dict(dom="replicas", n=9, lead="Nine cache instances front the API.",
     np="instances", ns="instance", vp="hold poisoned entries", vs="holds poisoned entries", vm="may hold poisoned entries",
     pi="a store with bad data inside", ni="a store whose contents are trustworthy",
     sa="each store carries bad data inside", sn="the contents of each store are trustworthy",
     mp="caches", loc="in the fleet"),
dict(dom="replicas", n=4, lead="Four snapshots exist for the volume.",
     np="snapshots", ns="snapshot", vp="are restorable", vs="is restorable", vm="may be restorable",
     pi="an image that can be brought back", ni="an image that cannot be brought back",
     sa="every image can be brought back", sn="no image can be brought back",
     mp="images", loc="for this volume"),
dict(dom="replicas", n=20, lead="Twenty edge caches replicate the config bundle.",
     np="caches", ns="cache", vp="picked up the new version", vs="picked up the new version", vm="may have picked up the new version",
     pi="a location now running the update", ni="a location still on the old release",
     sa="every location now runs the update", sn="each location remains on the old release",
     mp="locations", loc="at the edge"),
dict(dom="replicas", n=7, lead="Seven backup tapes cover the quarter.",
     np="tapes", ns="tape", vp="were verified", vs="was verified", vm="may have been verified",
     pi="a cartridge whose contents were confirmed good", ni="a cartridge nobody has confirmed",
     sa="every cartridge was confirmed good", sn="no cartridge has been confirmed",
     mp="cartridges", loc="in storage"),
# --- permissions ---
dict(dom="permissions", n=5, lead="Five tokens were issued to the reporting job.",
     np="tokens", ns="token", vp="carry write access", vs="carries write access", vm="may carry write access",
     pi="a credential that can modify data", ni="a credential restricted to reading",
     sa="every credential can modify data", sn="each credential is restricted to reading",
     mp="credentials", loc="for the job"),
dict(dom="permissions", n=3, lead="Three admin accounts remain from the migration.",
     np="accounts", ns="account", vp="were disabled", vs="was disabled", vm="may have been disabled",
     pi="a login that no longer works", ni="a login that still works",
     sa="every login has stopped working", sn="each login still works",
     mp="logins", loc="after the migration"),
dict(dom="permissions", n=8, lead="Eight API scopes are attached to the integration.",
     np="scopes", ns="scope", vp="exceed what the vendor documented", vs="exceeds what the vendor documented", vm="may exceed what the vendor documented",
     pi="a grant broader than the published spec", ni="a grant matching the published spec",
     sa="every grant is broader than the published spec", sn="each grant matches the published spec",
     mp="grants", loc="on the integration"),
dict(dom="permissions", n=4, lead="Four service keys rotate on the quarterly schedule.",
     np="keys", ns="key", vp="were rotated on time", vs="was rotated on time", vm="may have been rotated on time",
     pi="a secret refreshed by its deadline", ni="a secret now overdue for refresh",
     sa="every secret was refreshed by its deadline", sn="each secret is overdue for refresh",
     mp="secrets", loc="this quarter"),
dict(dom="permissions", n=6, lead="Six reviewers hold merge rights on the repository.",
     np="reviewers", ns="reviewer", vp="used their rights this month", vs="used their rights this month", vm="may have used their rights this month",
     pi="an approver who exercised the privilege recently", ni="an approver whose privilege sat unused",
     sa="every approver exercised the privilege recently", sn="each approver's privilege sat unused",
     mp="approvers", loc="on the project"),
dict(dom="permissions", n=2, lead="Two break-glass credentials exist for production.",
     np="credentials", ns="credential", vp="were exercised during the incident", vs="was exercised during the incident", vm="may have been exercised during the incident",
     pi="an emergency pass that got invoked", ni="an emergency pass that stayed sealed",
     sa="both emergency passes got invoked", sn="each emergency pass stayed sealed",
     mp="passes", loc="in production"),
dict(dom="permissions", n=9, lead="Nine bots have posting privileges in the workspace.",
     np="bots", ns="bot", vp="are rate-limited", vs="is rate-limited", vm="may be rate-limited",
     pi="an automation under a throttle", ni="an automation free of any throttle",
     sa="every automation sits under a throttle", sn="no automation has a throttle applied",
     mp="automations", loc="in the workspace"),
dict(dom="permissions", n=40, lead="Forty contractors were granted VPN access for the project.",
     np="contractors", ns="contractor", vp="retain access past the end date", vs="retains access past the end date", vm="may retain access past the end date",
     pi="an outside worker who can still connect", ni="an outside worker whose entry was closed",
     sa="every outside worker can still connect", sn="each outside worker's entry was closed",
     mp="outside workers", loc="on the roster"),
# --- recipients ---
dict(dom="recipients", n=7, lead="The rotation notice went to seven on-call staff.",
     np="staff", ns="staff member", vp="confirmed receipt", vs="confirmed receipt", vm="may have confirmed receipt",
     pi="a person who wrote back that it arrived", ni="a person from whom nothing came back",
     sa="every person wrote back that it arrived", sn="nothing came back from anyone",
     mp="people", loc="on the rotation"),
dict(dom="recipients", n=4, lead="Four customers were emailed the breach disclosure.",
     np="customers", ns="customer", vp="opened the message", vs="opened the message", vm="may have opened the message",
     pi="an addressee who viewed the notice", ni="an addressee who never viewed the notice",
     sa="every addressee viewed the notice", sn="no addressee has viewed the notice",
     mp="addressees", loc="so far"),
dict(dom="recipients", n=12, lead="Twelve subscribers get the weekly digest.",
     np="subscribers", ns="subscriber", vp="clicked through", vs="clicked through", vm="may have clicked through",
     pi="a reader who followed a link inside", ni="a reader who ignored the links entirely",
     sa="every reader followed a link inside", sn="each reader ignored the links entirely",
     mp="readers", loc="this week"),
dict(dom="recipients", n=3, lead="Three signers must countersign the release form.",
     np="signers", ns="signer", vp="have countersigned", vs="has countersigned", vm="may have countersigned",
     pi="a party whose signature is on file", ni="a party whose signature is still missing",
     sa="every required signature is on file", sn="each required signature is still missing",
     mp="parties", loc="on the form"),
dict(dom="recipients", n=5, lead="Five webhook endpoints subscribe to the event stream.",
     np="endpoints", ns="endpoint", vp="received the payload", vs="received the payload", vm="may have received the payload",
     pi="a listener the delivery reached", ni="a listener the delivery missed",
     sa="the delivery reached every listener", sn="the delivery missed every listener",
     mp="listeners", loc="downstream"),
dict(dom="recipients", n=2, lead="Two auditors were sent the quarterly evidence pack.",
     np="auditors", ns="auditor", vp="acknowledged it", vs="acknowledged it", vm="may have acknowledged it",
     pi="an examiner who responded", ni="an examiner who has stayed silent",
     sa="both examiners responded", sn="each examiner has stayed silent",
     mp="examiners", loc="this quarter"),
dict(dom="recipients", n=8, lead="Eight teams were invited to the architecture review.",
     np="teams", ns="team", vp="sent a delegate", vs="sent a delegate", vm="may have sent a delegate",
     pi="a group that showed up represented", ni="a group with an empty chair",
     sa="every group showed up represented", sn="each group left its chair empty",
     mp="groups", loc="at the review"),
dict(dom="recipients", n=6, lead="Six mirrors of the announcement were syndicated.",
     np="mirrors", ns="mirror", vp="rendered it correctly", vs="rendered it correctly", vm="may have rendered it correctly",
     pi="an outlet displaying the text faithfully", ni="an outlet displaying it garbled",
     sa="every outlet displays the text faithfully", sn="each outlet displays it garbled",
     mp="outlets", loc="across the web"),
# --- alerts ---
dict(dom="alerts", n=5, lead="Five monitors watch the payment path.",
     np="monitors", ns="monitor", vp="fired overnight", vs="fired overnight", vm="may have fired overnight",
     pi="a check that went off in the dark hours", ni="a check that stayed quiet",
     sa="every check went off in the dark hours", sn="each check stayed quiet",
     mp="checks", loc="on that path"),
dict(dom="alerts", n=3, lead="Three thresholds guard the disk usage metric.",
     np="thresholds", ns="threshold", vp="were breached", vs="was breached", vm="may have been breached",
     pi="a limit that got crossed", ni="a limit still holding",
     sa="every limit got crossed", sn="each limit is still holding",
     mp="limits", loc="on the metric"),
dict(dom="alerts", n=10, lead="Ten probes test the login flow every minute.",
     np="probes", ns="probe", vp="are timing out", vs="is timing out", vm="may be timing out",
     pi="a checker that stopped answering in time", ni="a checker still answering promptly",
     sa="every checker stopped answering in time", sn="each checker still answers promptly",
     mp="checkers", loc="against the flow"),
dict(dom="alerts", n=4, lead="Four pager policies route the weekend escalations.",
     np="policies", ns="policy", vp="were silenced for the holiday", vs="was silenced for the holiday", vm="may have been silenced for the holiday",
     pi="a path that was muted", ni="a path left active",
     sa="each path was muted", sn="each path was left active",
     mp="routes", loc="for the weekend"),
dict(dom="alerts", n=6, lead="Six canaries run against the checkout build.",
     np="canaries", ns="canary", vp="are red", vs="is red", vm="may be red",
     pi="a signal showing trouble", ni="a signal showing health",
     sa="every signal shows trouble", sn="each signal shows health",
     mp="signals", loc="on the build"),
dict(dom="alerts", n=2, lead="Two heartbeat feeds report from the standby site.",
     np="feeds", ns="feed", vp="went quiet", vs="went quiet", vm="may have gone quiet",
     pi="a pulse that stopped arriving", ni="a pulse still arriving",
     sa="both pulses stopped arriving", sn="each pulse is still arriving",
     mp="pulses", loc="from the site"),
dict(dom="alerts", n=9, lead="Nine dashboards track the release health.",
     np="dashboards", ns="dashboard", vp="show degraded numbers", vs="shows degraded numbers", vm="may show degraded numbers",
     pi="a panel with worrying figures", ni="a panel with reassuring figures",
     sa="every panel carries worrying figures", sn="each panel carries reassuring figures",
     mp="panels", loc="for the release"),
dict(dom="alerts", n=7, lead="Seven notification rules cover the billing queue.",
     np="rules", ns="rule", vp="have been muted", vs="has been muted", vm="may have been muted",
     pi="a trigger somebody switched off", ni="a trigger still armed",
     sa="every trigger was switched off", sn="each trigger remains armed",
     mp="triggers", loc="on the queue"),
# --- inventory ---
dict(dom="inventory", n=8, lead="Eight spare drives sit in the hardware locker.",
     np="drives", ns="drive", vp="are faulty", vs="is faulty", vm="may be faulty",
     pi="a disk that would not survive burn-in", ni="a disk fit for service",
     sa="every disk would flunk burn-in", sn="each disk is fit for service",
     mp="disks", loc="in the locker"),
dict(dom="inventory", n=4, lead="Four license seats remain on the analytics contract.",
     np="seats", ns="seat", vp="are already assigned", vs="is already assigned", vm="may be already assigned",
     pi="a slot somebody has claimed", ni="a slot still free to hand out",
     sa="every slot has been claimed", sn="each slot is still free to hand out",
     mp="slots", loc="on the contract"),
dict(dom="inventory", n=6, lead="Six laptops came back from the offboarding wave.",
     np="laptops", ns="laptop", vp="were wiped", vs="was wiped", vm="may have been wiped",
     pi="a machine scrubbed of its data", ni="a machine with data still on it",
     sa="every machine was scrubbed of its data", sn="each machine still has data on it",
     mp="machines", loc="from the wave"),
dict(dom="inventory", n=3, lead="Three replacement routers arrived for the branch office.",
     np="routers", ns="router", vp="passed acceptance testing", vs="passed acceptance testing", vm="may have passed acceptance testing",
     pi="a unit cleared for deployment", ni="a unit rejected at intake",
     sa="every unit was cleared for deployment", sn="each unit was rejected at intake",
     mp="units", loc="at the branch"),
dict(dom="inventory", n=5, lead="Five domain names renew this cycle.",
     np="domains", ns="domain", vp="auto-renewed", vs="auto-renewed", vm="may have auto-renewed",
     pi="a registration that extended itself", ni="a registration heading toward expiry",
     sa="every registration extended itself", sn="each registration is heading toward expiry",
     mp="registrations", loc="this cycle"),
dict(dom="inventory", n=2, lead="Two hardware security modules anchor the signing service.",
     np="modules", ns="module", vp="are past end-of-support", vs="is past end-of-support", vm="may be past end-of-support",
     pi="a device the maker no longer maintains", ni="a device still under maintenance",
     sa="both devices are beyond maintenance", sn="each device remains under maintenance",
     mp="devices", loc="in the service"),
dict(dom="inventory", n=9, lead="Nine SSL certificates cover the public estate.",
     np="certificates", ns="certificate", vp="expire this month", vs="expires this month", vm="may expire this month",
     pi="a cert running out within weeks", ni="a cert with a long runway",
     sa="every cert runs out within weeks", sn="each cert has a long runway",
     mp="certs", loc="on the estate"),
dict(dom="inventory", n=7, lead="Seven container base images are pinned in the registry.",
     np="images", ns="image", vp="carry known CVEs", vs="carries known CVEs", vm="may carry known CVEs",
     pi="a foundation layer with published flaws", ni="a foundation layer with a clean advisory record",
     sa="each foundation layer has published flaws", sn="each foundation layer has a clean advisory record",
     mp="bases", loc="in the registry"),
# --- ordinary human situations ---
dict(dom="ordinary", n=6, lead="Six guests RSVP'd for Saturday's dinner.",
     np="guests", ns="guest", vp="are vegetarian", vs="is vegetarian", vm="may be vegetarian",
     pi="a diner who avoids meat", ni="a diner who eats meat",
     sa="every diner avoids meat", sn="each diner eats meat",
     mp="diners", loc="at the table"),
dict(dom="ordinary", n=4, lead="Four housemates split the utility bills.",
     np="housemates", ns="housemate", vp="paid their share", vs="paid their share", vm="may have paid their share",
     pi="a person whose portion is settled", ni="a person whose portion is outstanding",
     sa="every portion is settled", sn="each portion is outstanding",
     mp="portions", loc="this month"),
dict(dom="ordinary", n=3, lead="Three referees agreed to review the grant application.",
     np="referees", ns="referee", vp="submitted their reports", vs="submitted their report", vm="may have submitted their report",
     pi="an assessor whose write-up came in", ni="an assessor whose write-up is missing",
     sa="every write-up came in", sn="each write-up is missing",
     mp="assessors", loc="by the deadline"),
dict(dom="ordinary", n=8, lead="Eight seedlings went into the garden bed.",
     np="seedlings", ns="seedling", vp="took root", vs="took root", vm="may have taken root",
     pi="a plant that established itself", ni="a plant that withered",
     sa="every plant established itself", sn="each plant withered",
     mp="plants", loc="in the bed"),
dict(dom="ordinary", n=5, lead="Five library books are due back Friday.",
     np="books", ns="book", vp="have been renewed", vs="has been renewed", vm="may have been renewed",
     pi="a title with an extended loan", ni="a title still on the original clock",
     sa="every title got an extended loan", sn="each title sits on the original clock",
     mp="titles", loc="on the account"),
dict(dom="ordinary", n=2, lead="Two cars share the family driveway.",
     np="cars", ns="car", vp="failed the emissions test", vs="failed the emissions test", vm="may have failed the emissions test",
     pi="a vehicle that flunked the inspection", ni="a vehicle that cleared the inspection",
     sa="both vehicles flunked the inspection", sn="each vehicle cleared the inspection",
     mp="vehicles", loc="this year"),
dict(dom="ordinary", n=7, lead="Seven students turned in the take-home exam.",
     np="students", ns="student", vp="cited the optional reading", vs="cited the optional reading", vm="may have cited the optional reading",
     pi="a paper drawing on the extra material", ni="a paper ignoring the extra material",
     sa="every paper draws on the extra material", sn="each paper ignores the extra material",
     mp="papers", loc="in the pile"),
dict(dom="ordinary", n=12, lead="Twelve jars of preserves came out of the weekend batch.",
     np="jars", ns="jar", vp="sealed properly", vs="sealed properly", vm="may have sealed properly",
     pi="a container whose lid took", ni="a container whose lid did not take",
     sa="every lid took", sn="no lid took",
     mp="containers", loc="in the batch"),
]
assert len(SC) == 56, len(SC)
