#!/usr/bin/env python3
"""Authored 32-pair bank for the no-undo / can-undo R* successor (a-mv841prke9x9e5cm), 2026-09-25.
Census into the frozen frame (noundo_rstar.py): 16 no-undo (8 report / 8 instruction), 16 can-undo on the joint
slot schedule, ACTION word counts 3:6 4:8 5:8 6:6 7:4. Each row carries the semantic claim the row-by-row review
must check. English arms are generated by R* (v3) and must be byte-equal on validation. No tokenizer here."""
import json, sys, importlib.util
spec = importlib.util.spec_from_file_location("nr", "/home/user/claude-projects/Reticuli/panel-artifacts/no-undo-rstar-2026-09-22/noundo_rstar.py")
nr = importlib.util.module_from_spec(spec); spec.loader.exec_module(nr)

# (shape, action, review)  -- no-undo: no path back within the WRITER's reach at write time
NO_UNDO = [
 ("report","Rotated the signing key","The previous private key was destroyed by the rotation; signatures verify only against the new key. Re-issuing the old key is impossible, and issuing another key is a new change."),
 ("report","Published 1.4.0 to npm","A published version number is never reusable on npm; unpublish removes the tarball but does not return the registry to a state where 1.4.0 is unpublished-and-available, and consumers may have fetched it."),
 ("report","Sent the invoice to the client","A sent message cannot be unsent; a correction or credit note is a new message, not a return to the pre-send state."),
 ("report","Purged the March audit log","Retention policy on this system keeps no copy of purged audit rows; nothing within the writer's reach restores them."),
 ("report","Posted the apology","A public post has been read once posted; deleting it is a later corrective act, not a return to the unposted state."),
 ("report","Shredded the ballots","Physical destruction; no path."),
 ("report","Broadcast the emergency alert to all residents","Recipients have received it; a follow-up message is a new act."),
 ("report","Ran the destructive schema migration on production","Dexagon's compensation case: the down migration restores the SCHEMA but not the rows written or dropped since, so the immediate pre-action state is not recoverable; a partial return is no-undo, and the recovery that does exist is described in words in the review, not in a slot."),
 ("instruction","Rotate the recovery codes","Old codes are invalidated on rotation; the pre-rotation set cannot be reinstated."),
 ("instruction","Announce the layoffs at noon","Once announced, unannouncing is not available; retraction is a new act."),
 ("instruction","Wipe the laptop","Full-disk wipe of a device with no backup taken (stated in the shared case); nothing within the writer's reach restores the contents."),
 ("instruction","Submit the tax filing","A filed return is on record; an amended return is a new filing, not a withdrawal of the first."),
 ("instruction","Burn the remaining test tokens","Burned tokens are removed from supply; minting new ones is a new change."),
 ("instruction","Release the embargoed report now","Release ends the embargo; it cannot be re-imposed on readers who have the report."),
 ("instruction","Overwrite the only copy of the export","The only copy is gone once overwritten; the shared case states no other copy exists."),
 ("instruction","Delete the customer account permanently","Hard delete, 'permanently' carried in the ACTION; no restore path within the writer's reach."),
]
# (shape, action, path, holder, window, cost, review) -- can-undo: PATH returns the WHOLE immediate pre-action state
CAN_UNDO = [
 # path-only x3
 ("report","Archived the old workspace","unarchiving from the workspace menu",None,None,None,"Archiving is a flag; unarchive returns the workspace exactly as it was. Writer's own hand."),
 ("instruction","Mute the channel","the unmute toggle",None,None,None,"Mute is a flag; unmute is the same toggle. Writer's own hand."),
 ("report","Disabled the nightly backup verification job","re-enabling it in the scheduler",None,None,None,"The pre-action state is 'job enabled'; re-enabling restores it. Runs missed while disabled are consequences after the act, not part of the pre-action state."),
 # window-only x3
 ("report","Deleted the merged branches","the pull request restore button",None,"30d",None,"The hosting platform restores the deleted branch ref at its last commit from the pull request page for 30 days (stated platform note in the shared case); writer's own hand."),
 ("instruction","Move the file to trash","the trash folder",None,"30d",None,"Trash restore returns the file to its original location with metadata; the trash empties after 30 days."),
 ("report","Closed the ticket","the reopen link",None,"7d",None,"Reopen returns the ticket to its open state; the link expires after 7 days per the tracker's rule in the shared case."),
 # holder-only x3
 ("report","Suspended the vendor account","the admin console","the platform operator",None,None,"Unsuspend in the admin console restores the account's prior active state; only the platform operator has the console, so the holder is named and the writer cannot do it alone."),
 ("instruction","Deactivate the contractor's building access badge","reactivation at the security desk","the security desk",None,None,"The badge is deactivated, not destroyed; the security desk can reactivate the same badge, restoring the prior access state. Not a reissue."),
 ("report","Hid the public pricing page","the publish switch","the site editor",None,None,"Hide is a visibility flag; the site editor's publish switch restores the page as it was."),
 # cost-only x2
 ("report","Unpublished the paid course listing","republishing from the dashboard",None,None,"25 usd","Republishing restores the same listing (content, reviews, enrolment link) as before; the marketplace charges a 25 usd relisting fee, stated in the shared case. Writer's own hand."),
 ("instruction","Pause the campaign","the resume button",None,None,"5 credits","Pausing spends nothing; resume returns the campaign to running with the same budget and schedule; the platform charges 5 credits to resume (shared case)."),
 # holder+window x2
 ("report","Locked the shared drive for everyone","the unlock request form","the drive owner","14d",None,"Dexagon 76aef166: the recovery route is the drive owner's unlock action, reached through the request form, and in this hypothetical case the owner-operated unlock restores the prior access state exactly for 14 days after the lock, after which the drive's lock becomes permanent policy; the deadline binds completion of the unlock, not submission of the form, so a form submitted on day 14 that is not actioned is NOT a recovery. Only the drive owner holds the action. Case note only; the pair and the profile are unchanged."),
 ("instruction","Freeze the payroll run","the unfreeze action","the finance lead","2h",None,"Unfreeze returns the run to its pre-freeze scheduled state; only the finance lead holds the action, and it is available until the 2-hour bank cutoff."),
 # holder+cost x1
 ("instruction","Stop the paid tunnel to staging","restarting it in the dashboard","the account admin",None,"3 credits","Restart returns the tunnel to up on the same endpoint; only the account admin can restart a paid tunnel, and a restart costs 3 credits."),
 # window+cost x1
 ("instruction","Release the reserved domain to the registry","the registry redemption process",None,"30d","80 usd","Dexagon 76aef166: PATH is the recovery OPERATION, not the time allowance. The registry redemption process restores the registration to the same registrant; the 30-day window and the 80 usd fee are the stated hypothetical case facts, carried identically in both arms, not a cited universal registry policy. Writer's own hand."),
 # holder+window+cost x1
 ("instruction","Drop the hold on the shipment","a re-hold request","the warehouse lead","1d","2 credits","A re-hold before dispatch restores the held state; only the warehouse lead can place it, dispatch is in 1 day, and the system charges 2 credits per hold change."),
]
pairs, review = [], []
for shape, action, rv in NO_UNDO:
    f = {"stratum":"no-undo","action":action}
    pairs.append({"ainglish": nr.render_marked(f), "english": nr.render_rstar(f), "shape": shape})
    review.append({"row": len(pairs), "stratum":"no-undo","shape":shape,"category":"no-undo","action":action,"claim":"no path back to the immediate pre-action state within the writer's reach at write time","review":rv})
for shape, action, path, holder, window, cost, rv in CAN_UNDO:
    f = {"stratum":"can-undo","action":action,"path":path}
    if holder: f["holder"]=holder
    if window: f["window"]=window
    if cost: f["cost"]=cost
    pairs.append({"ainglish": nr.render_marked(f), "english": nr.render_rstar(f), "shape": shape})
    review.append({"row": len(pairs), "stratum":"can-undo","shape":shape,"category":nr.category(f),"action":action,"path":path,"holder":holder or "(writer)","window":window,"cost":cost,"claim":"PATH returns the whole immediate pre-action state under the stated holder, window and cost","review":rv})
rep = nr.validate_bank(pairs)
json.dump(pairs, open("bank.json","w"), indent=1, ensure_ascii=False)
json.dump(rep["sampling_profile"], open("profile.json","w"), indent=1)
json.dump(review, open("review.json","w"), indent=1, ensure_ascii=False)
print("VALID", {k:v for k,v in rep.items() if k!='sampling_profile'})
print("profile cells:", len(rep["sampling_profile"]))
for p in pairs: print("  ", p["shape"][:4], "|", p["ainglish"], "||", p["english"])
